#!/bin/sh

# Purpose: find a terminal emulator in the system and forward our parameters to it


TERM_EMU="$(which xterm 2>/dev/null)"
if [ -n "${TERM_EMU}" ]; then
    exec "$TERM_EMU" -hold -e "$@"
fi
TERM_EMU="$(which gnome-terminal 2>/dev/null)"
if [ -n "${TERM_EMU}" ]; then
    CMD="$@"
    exec "$TERM_EMU" -x sh -c "${CMD}; read"
fi


if [ -n "${TERM_EMU}" ]; then
    echo "selected term is ${TERM_EMU}"
else
    echo 1>&2 "Error: didn't find a terminal emulator"
    exit 1
fi
