#!/bin/sh

filename=$0

if [ "$1" = "-licenseFile" ]; then
	RTI_LICENSE_FILE=$2
fi

export RTI_LICENSE_FILE

scriptDir=`dirname "$filename"`

RTI_ANALYZER_ROOT_DIR=$scriptDir/..

RTI_ANALYZER_VERSION=5.1.0

RTI_ANALYZER_HOME="$RTI_ANALYZER_ROOT_DIR/apps/RTI_Analyzer_$RTI_ANALYZER_VERSION"

JRE_HOME="$RTI_ANALYZER_ROOT_DIR/jre"

RTI_JAVA="$JRE_HOME"/bin/java

osver=`uname -r`

case $osver in
    2.6* | 3.*)
        LD_LIBRARY_PATH=$RTI_ANALYZER_ROOT_DIR/lib/i86Linux2.6gcc4.1.1jdk:$JRE_HOME/lib/i386:$LD_LIBRARY_PATH
    ;;
    *)
        LD_LIBRARY_PATH=$RTI_ANALYZER_ROOT_DIR/lib/i86Linux2.4gcc3.2.2jdk:$JRE_HOME/lib/i386:$LD_LIBRARY_PATH
    ;;
esac

export LD_LIBRARY_PATH
export RTI_ANALYZER_ROOT_DIR

"$RTI_ANALYZER_HOME"/eclipse/rtianalyzer -vm "$RTI_JAVA" -data ${HOME}/rti/workspaces/RTI_Analyzer_$RTI_ANALYZER_VERSION
