#!/bin/sh

# -------------- Path --------------
filename=$0
scriptsDir=`dirname "$filename"`
if [ -d "$scriptsDir/../lib/i86Linux2.6gcc4.1.1jdk" ]; then
    DDS_SO_DIR=$scriptsDir/../lib/i86Linux2.6gcc4.1.1jdk
else
    DDS_SO_DIR=$scriptsDir/../lib/x64Linux2.6gcc4.1.1jdk
fi
LD_LIBRARY_PATH=$DDS_SO_DIR:$scriptsDir/../jre/bin:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
# ----------------------------------


RTI_ADMIN_CONSOLE_VERSION=5.1.0

$scriptsDir/../apps/RTI_AdminConsole -vm $scriptsDir/../jre/bin/java -data ${HOME}/rti/workspaces/RTI_AdminConsole_$RTI_ADMIN_CONSOLE_VERSION $@
