#!/bin/sh
#
# (c) Copyright, Real-Time Innovations, $Date: 2013/10/24 20:23:17 $.
# All rights reserved.
# No duplications, whole or partial, manual or electronic, may be made
# without express written permission.  Any such copies, or
# revisions thereof, must display this notice unaltered.
# This code contains trade secrets of Real-Time Innovations, Inc.
#
#Modification history
#-------------------
# 2.0a,32jul10,jpl Rewrite, changed to bash, can now launch from arbitrary
#		   directory.
# 1.0a,15dec09,krb Initial version
########################################################################

# Launches RTI Monitor

# BASE_DIR: the directory which holds the RTI Monitor distribution
filename=$0

scriptDir=`dirname "$filename"`

BASE_DIR=$scriptDir/..

# Determine the architecture
OS=`uname`
OS_VER=`uname -r`
OS_SIZE=`uname -i`

if test "$OS_SIZE" = "unknown"; then
    OS_SIZE=`uname -m`
fi

if [ "$1" = "-licenseFile" ]; then
	RTI_LICENSE_FILE=$2
	# Null out CLI that monitor does not understand
	shift
	shift
fi

export RTI_LICENSE_FILE

# RTI_DDS_DIR: the directory which holds the version of RTI Data Distribution 
# Service that is to be used

# RTI_JAVA_HOME: the directory which contains the Java Runtime Environment to be
# used

# RTI_DDS_JAVA_ARCH: the platform's java architecture.
# For example, i86Linux2.6gcc4.1.1jdk

case $OS in
Linux*)
    case $OS_VER in
    2.6* | 3.*)
        if test "$OS_SIZE" = "i386" ; then
	    RTI_DDS_DIR=$BASE_DIR
	    RTI_DDS_JAVA_ARCH=i86Linux2.6gcc4.1.1jdk    
	    RTI_JAVA_DIR=$BASE_DIR/jre/i86Linux/bin
        elif test "$OS_SIZE" = "x86_64" ; then
	    RTI_DDS_DIR=$BASE_DIR
	    RTI_DDS_JAVA_ARCH=x64Linux2.6gcc4.1.1jdk
	    RTI_JAVA_DIR=$BASE_DIR/jre/x64Linux/bin
        elif test "$OS_SIZE" = "i686" ; then
            RTI_DDS_DIR=$BASE_DIR
            RTI_DDS_JAVA_ARCH=i86Linux2.6gcc4.1.1jdk
            RTI_JAVA_DIR=$BASE_DIR/jre/i86Linux/bin
	else
	    echo "Operating System version ($OS_SIZE) not understood and/or not officially supported by RTI Monitor"
	fi;;
    *)
	echo "Operating System version ($OS_VER) not understood and/or not officially supported by RTI Monitor"
	;;
    esac
    ;;
*)
    echo "Operating System ($OS) not understood and/or not officially supported by RTI Monitor"
    ;;
esac

if [ x$RTI_DDS_DIR = x ]; then
    exit
fi
if [ x$RTI_DDS_JAVA_ARCH = x ]; then
    exit
fi
if [ x$RTI_JAVA_DIR = x ]; then
    exit
fi

# DEBUG_LIBS: a quick way to enable debug libraries. 
#             set this to 'd' (without the ticks) to enable them.
DEBUG_LIBS=

#-------------------------------------------------------------------------------
# The variables below generally do not have to be adjusted

RTI_DDS_JAR=$RTI_DDS_DIR/class/nddsjava$DEBUG_LIBS.jar

RTI_DDS_JAVA_DIR=$RTI_DDS_DIR/lib/$RTI_DDS_JAVA_ARCH

MONITOR_JAR=$BASE_DIR/lib/rtimonitor$DEBUG_LIBS.jar
MONITOR_LIB_JAR=$BASE_DIR/lib/rtiddsmonitorlib$DEBUG_LIBS.jar
JFREECHART_JARS=$BASE_DIR/lib/jcommon-1.0.16.jar:$BASE_DIR/lib/jfreechart-1.0.13.jar
LOG4J_JAR=$BASE_DIR/lib/log4j-1.2.9.jar
SWINGX_JAR=$BASE_DIR/lib/swingx-1.6.jar
DISTLOGDATAMODEL_JAR=$BASE_DIR/lib/distlogdatamodel.jar

JAVA_CLASSPATH=$MONITOR_JAR:$MONITOR_LIB_JAR:$JFREECHART_JARS:$LOG4J_JAR:$SWINGX_JAR:$DISTLOGDATAMODEL_JAR:$RTI_DDS_JAR

if [ $?LD_LIBRARY_PATH ]; then
    LD_LIBRARY_PATH=$RTI_DDS_JAVA_DIR:$LD_LIBRARY_PATH
else
    LD_LIBRARY_PATH=$RTI_DDS_JAVA_DIR
fi

export LD_LIBRARY_PATH

RTI_MONITOR_VERSION=5.1.0

NDDS_QOS_PROFILES=$BASE_DIR/config/rtimonitor_qos_profiles.xml
export NDDS_QOS_PROFILES

# use this argument to Java to enable remote monitoring
#-Dcom.sun.management.jmxremote
$RTI_JAVA_DIR/java  -Xmx500m \
    -Dcom.sun.management.jmxremote \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -classpath $JAVA_CLASSPATH \
    -DRTI_MONITOR_DIR=$BASE_DIR \
    -DRTI_MONITOR_LOG_DIR=${HOME}/rti/workspaces/RTI_Monitor_$RTI_MONITOR_VERSION \
    com.rti.dds.monitor.ui.DdsMonitorManager $@ &
